from bio_enums import BioOrientation

# File for defining alphabets (e.g. DNA, RNA, Protein)
# Also defines complementary bases

# TODO: Inosine? (i)
NTs = {
    "A", "T", "G", "C", "a", "t", "g", "c",                      # Standard
    "W", "S", "M", "K", "R", "Y", "w", "s", "m", "k", "r", "y",  # Doubles
    "B", "D", "H", "V", "b", "d", "h", "v",                      # Triples
    "N", "n",                                                    # Any
    "X", "x"                                                     # Undefined
}

nt_complements = {
    "A" : "T", "T" : "A", "G" : "C", "C" : "G",
    "S" : "S", "W" : "W", "M" : "K", "K" : "M",
    "R" : "Y", "Y" : "R", "B" : "V", "V" : "B",
    "D" : "H", "H" : "D", "N" : "N",
    "X" : "X"
}

# TODO: Can I just use keys for the dicts as a way to get the specific proteins etc?

AAs = {
    "A", "C", "D", "E", "F",
    "G", "H", "I", "K", "L",
    "M", "N", "P", "Q", "R",
    "S", "T", "V", "W", "Y",
    "X" # Undefined
}

RNA_NTs = {
    "A", "G", "C", "U",
    "X" # Undefined
}

rna_complements = {
    "A":"U", "U":"A", "G":"C", "C":"G"
}

dna_to_rna = {
    "A":"A",
    "T":"U",
    "G":"G",
    "C":"C"
}

aa_codons = {
    "A":["GCT","GCC","GCA","GCG"],
    "C":["TGT","TGC"],
    "D":["GAT","GAC"],
    "E":["GAA","GAG"],
    "F":["TTT","TTC"],
    "G":["GGT","GGC","GGA","GGG"],
    "H":["CAT","CAC"],
    "I":["ATT","ATC","ATA"],
    "K":["AAA","AAG"],
    "L":["TTA","TTG","CTT","CTC","CTA","CTG"],
    "M":["ATG"],
    "N":["AAT","AAC"],
    "P":["CCT","CCC","CCA","CCG"],
    "Q":["CAA","CAG"],
    "R":["CGT","CGC","CGA","CGG","AGA","AGG"],
    "S":["TCT","TCC","TCA","TCG","AGT","AGC"],
    "T":["ACT","ACC","ACA","ACG"],
    "V":["GTT","GTC","GTA","GTG"],
    "W":["TGG"],
    "Y":["TAT","TAC"],
    "*":["TGA","TAA","TAG"] # Stop codons
}

codon_AAs = {
    "AAA":"K", "AAG":"K", "AAT":"N", "AAC":"N",
    "AGA":"R", "AGG":"R", "AGT":"S", "AGC":"S",
    "ATA":"I", "ATG":"M", "ATT":"I", "ATC":"I",
    "ACA":"T", "ACG":"T", "ACT":"T", "ACC":"T",
    "GAA":"E", "GAG":"E", "GAT":"D", "GAC":"D",
    "GGA":"G", "GGG":"G", "GGT":"G", "GGC":"G",
    "GTA":"V", "GTG":"V", "GTT":"V", "GTC":"V",
    "GCA":"A", "GCG":"A", "GCT":"A", "GCC":"A",
    "TAA":"*", "TAG":"*", "TAT":"Y", "TAC":"Y",
    "TGA":"*", "TGG":"W", "TGT":"C", "TGC":"C",
    "TTA":"L", "TTG":"L", "TTT":"F", "TTC":"F",
    "TCA":"S", "TCG":"S", "TCT":"S", "TCC":"S",
    "CAA":"Q", "CAG":"Q", "CAT":"H", "CAC":"H",
    "CGA":"R", "CGG":"R", "CGT":"R", "CGC":"R",
    "CTA":"L", "CTG":"L", "CTT":"L", "CTC":"L",
    "CCA":"P", "CCG":"P", "CCT":"P", "CCC":"P"
}

rna_codon_AAs = {
    "AAA":"K", "AAG":"K", "AAU":"N", "AAC":"N",
    "AGA":"R", "AGG":"R", "AGU":"S", "AGC":"S",
    "AUA":"I", "AUG":"M", "AUU":"I", "AUC":"I",
    "ACA":"T", "ACG":"T", "ACU":"T", "ACC":"T",
    "GAA":"E", "GAG":"E", "GAU":"D", "GAC":"D",
    "GGA":"G", "GGG":"G", "GGU":"G", "GGC":"G",
    "GUA":"V", "GUG":"V", "GUU":"V", "GUC":"V",
    "GCA":"A", "GCG":"A", "GCU":"A", "GCC":"A",
    "UAA":"*", "UAG":"*", "UAU":"Y", "UAC":"Y",
    "UGA":"*", "UGG":"W", "UGU":"C", "UGC":"C",
    "UUA":"L", "UUG":"L", "UUU":"F", "UUC":"F",
    "UCA":"S", "UCG":"S", "UCU":"S", "UCC":"S",
    "CAA":"Q", "CAG":"Q", "CAU":"H", "CAC":"H",
    "CGA":"R", "CGG":"R", "CGU":"R", "CGC":"R",
    "CUA":"L", "CUG":"L", "CUU":"L", "CUC":"L",
    "CCA":"P", "CCG":"P", "CCU":"P", "CCC":"P"
}

aa_rna_codons = {
    "A":["GCU","GCC","GCA","GCG"],
    "C":["UGU","UGC"],
    "D":["GAU","GAC"],
    "E":["GAA","GAG"],
    "F":["UUU","UUC"],
    "G":["GGU","GGC","GGA","GGG"],
    "H":["CAU","CAC"],
    "I":["AUU","AUC","AUA"],
    "K":["AAA","AAG"],
    "L":["UUA","UUG","CUU","CUC","CUA","CUG"],
    "M":["AUG"],
    "N":["AAU","AAC"],
    "P":["CCU","CCC","CCA","CCG"],
    "Q":["CAA","CAG"],
    "R":["CGU","CGC","CGA","CGG","AGA","AGG"],
    "S":["UCU","UCC","UCA","UCG","AGU","AGC"],
    "T":["ACU","ACC","ACA","ACG"],
    "V":["GUU","GUC","GUA","GUG"],
    "W":["UGG"],
    "Y":["UAU","UAC"],
    "*":["UGA","UAA","UAG"] # Stop codons
}

AAV_seqs = { 
    "AAV2":"MAADGYLPDWLEDTLSEGIRQWWKLKPGPPPPKPAERHKDDSRGLVLPGYKYLGPFNGLDKGEPVNEADAAALEHDKAYDRQLDSGDNPYLKYNHADAEFQERLKEDTSFGGNLGRAVFQAKKRVLEPLGLVEEPVKTAPGKKRPVEHSPVEPDSSSGTGKAGQQPARKRLNFGQTGDADSVPDPQPLGQPPAAPSGLGTNTMATGSGAPMADNNEGADGVGNSSGNWHCDSTWMGDRVITTSTRTWALPTYNNHLYKQISSQSGASNDNHYFGYSTPWGYFDFNRFHCHFSPRDWQRLINNNWGFRPKRLNFKLFNIQVKEVTQNDGTTTIANNLTSTVQVFTDSEYQLPYVLGSAHQGCLPPFPADVFMVPQYGYLTLNNGSQAVGRSSFYCLEYFPSQMLRTGNNFTFSYTFEDVPFHSSYAHSQSLDRLMNPLIDQYLYYLSRTNTPSGTTTQSRLQFSQAGASDIRDQSRNWLPGPCYRQQRVSKTSADNNNSEYSWTGATKYHLNGRDSLVNPGPAMASHKDDEEKFFPQSGVLIFGKQGSEKTNVDIEKVMITDEEEIRTTNPVATEQYGSVSTNLQRGNRQAATADVNTQGVLPGMVWQDRDVYLQGPIWAKIPHTDGHFHPSPLMGGFGLKHPPPQILIKNTPVPANPSTTFSAAKFASFITQYSTGQVSVEIEWELQKENSKRWNPEIQYTSNYNKSVNVDFTVDTNGVYSEPRPIGTRYLTRNL",
    "AAV4":"MTDGYLPDWLEDNLSEGVREWWALQPGAPKPKANQQHQDNARGLVLPGYKYLGPGNGLDKGEPVNAADAAALEHDKAYDQQLKAGDNPYLKYNHADAEFQQRLQGDTSFGGNLGRAVFQAKKRVLEPLGLVEQAGETAPGKKRPLIESPQQPDSSTGIGKKGKQPAKKKLVFEDETGAGDGPPEGSTSGAMSDDSEMRAAAGGAAVEGGQGADGVGNASGDWHCDSTWSEGHVTTTSTRTWVLPTYNNHLYKRLGESLQSNTYNGFSTPWGYFDFNRFHCHFSPRDWQRLINNNWGMRPKAMRVKIFNIQVKEVTTSNGETTVANNLTSTVQIFADSSYELPYVMDAGQEGSLPPFPNDVFMVPQYGYCGLVTGNTSQQQTDRNAFYCLEYFPSQMLRTGNNFEITYSFEKVPFHSMYAHSQSLDRLMNPLIDQYLWGLQSTTTGTTLNAGTATTNFTKLRPTNFSNFKKNWLPGPSIKQQGFSKTANQNYKIPATGSDSLIKYETHSTLDGRWSALTPGPPMATAGPADSKFSNSQLIFAGPKQNGNTATVPGTLIFTSEEELAATNATDTDMWGNLPGGDQSNSNLPTVDRLTALGAVPGMVWQNRDIYYQGPIWAKIPHTDGHFHPSPLIGGFGLKHPPPQIFIKNTPVPANPATTFSSTPVNSFITQYSTGQVSVQIDWEIQKERSKRWNPEVQFTSNYGQQNSLLWAPDAAGKYTEPRAIGTRYLTHHL",
    "AAV5":"MSFVDHPPDWLEEVGEGLREFLGLEAGPPKPKPNQQHQDQARGLVLPGYNYLGPGNGLDRGEPVNRADEVAREHDISYNEQLEAGDNPYLKYNHADAEFQEKLADDTSFGGNLGKAVFQAKKRVLEPFGLVEEGAKTAPTGKRIDDHFPKRKKARTEEDSKPSTSSDAEAGPSGSQQLQIPAQPASSLGADTMSAGGGGPLGDNNQGADGVGNASGDWHCDSTWMGDRVVTKSTRTWVLPSYNNHQYREIKSGSVDGSNANAYFGYSTPWGYFDFNRFHSHWSPRDWQRLINNYWGFRPRSLRVKIFNIQVKEVTVQDSTTTIANNLTSTVQVFTDDDYQLPYVVGNGTEGCLPAFPPQVFTLPQYGYATLNRDNTENPTERSSFFCLEYFPSKMLRTGNNFEFTYNFEEVPFHSSFAPSQNLFKLANPLVDQYLYRFVSTNNTGGVQFNKNLAGRYANTYKNWFPGPMGRTQGWNLGSGVNRASVSAFATTNRMELEGASYQVPPQPNGMTNNLQGSNTYALENTMIFNSQPANPGTTATYLEGNMLITSESETQPVNRVAYNVGGQMATNNQSSTTAPATGTYNLQEIVPGSVWMERDVYLQGPIWAKIPETGAHFHPSPAMGGFGLKHPPPMMLIKNTPVPGNITSFSDVPVSSFITQYSTGQVTVEMEWELKKENSKRWNPEIQYTNNYNDPQFVDFAPDSTGEYRTTRPIGTRYLTRPL",
    "AAV7":"MAADGYLPDWLEDNLSEGIREWWDLKPGAPKPKANQQKQDNGRGLVLPGYKYLGPFNGLDKGEPVNAADAAALEHDKAYDQQLKAGDNPYLRYNHADAEFQERLQEDTSFGGNLGRAVFQAKKRVLEPLGLVEEGAKTAPAKKRPVEPSPQRSPDSSTGIGKKGQQPARKRLNFGQTGDSESVPDPQPLGEPPAAPSSVGSGTVAAGGGAPMADNNEGADGVGNASGNWHCDSTWLGDRVITTSTRTWALPTYNNHLYKQISSETAGSTNDNTYFGYSTPWGYFDFNRFHCHFSPRDWQRLINNNWGFRPKKLRFKLFNIQVKEVTTNDGVTTIANNLTSTIQVFSDSEYQLPYVLGSAHQGCLPPFPADVFMIPQYGYLTLNNGSQSVGRSSFYCLEYFPSQMLRTGNNFEFSYSFEDVPFHSSYAHSQSLDRLMNPLIDQYLYYLARTQSNPGGTAGNRELQFYQGGPSTMAEQAKNWLPGPCFRQQRVSKTLDQNNNSNFAWTGATKYHLNGRNSLVNPGVAMATHKDDEDRFFPSSGVLIFGKTGATNKTTLENVLMTNEEEIRPTNPVATEEYGIVSSNLQAANTAAQTQVVNNQGALPGMVWQNRDVYLQGPIWAKIPHTDGNFHPSPLMGGFGLKHPPPQILIKNTPVPANPPEVFTPAKFASFITQYSTGQVSVEIEWELQKENSKRWNPEIQYTSNFEKQTGVDFAVDSQGVYSEPRPIGTRYLTRNL",
    "AAV8":"MAADGYLPDWLEDNLSEGIREWWALKPGAPKPKANQQKQDDGRGLVLPGYKYLGPFNGLDKGEPVNAADAAALEHDKAYDQQLQAGDNPYLRYNHADAEFQERLQEDTSFGGNLGRAVFQAKKRVLEPLGLVEEGAKTAPGKKRPVEPSPQRSPDSSTGIGKKGQQPARKRLNFGQTGDSESVPDPQPLGEPPAAPSGVGPNTMAAGGGAPMADNNEGADGVGSSSGNWHCDSTWLGDRVITTSTRTWALPTYNNHLYKQISNGTSGGATNDNTYFGYSTPWGYFDFNRFHCHFSPRDWQRLINNNWGFRPKRLSFKLFNIQVKEVTQNEGTKTIANNLTSTIQVFTDSEYQLPYVLGSAHQGCLPPFPADVFMIPQYGYLTLNNGSQAVGRSSFYCLEYFPSQMLRTGNNFQFTYTFEDVPFHSSYAHSQSLDRLMNPLIDQYLYYLSRTQTTGGTANTQTLGFSQGGPNTMANQAKNWLPGPCYRQQRVSTTTGQNNNSNFAWTAGTKYHLNGRNSLANPGIAMATHKDDEERFFPSNGILIFGKQNAARDNADYSDVMLTSEEEIKTTNPVATEEYGIVADNLQQQNTAPQIGTVNSQGALPGMVWQNRDVYLQGPIWAKIPHTDGNFHPSPLMGGFGLKHPPPQILIKNTPVPADPPTTFNQSKLNSFITQYSTGQVSVEIEWELQKENSKRWNPEIQYTSNYYKSTSVDFAVNTEGVYSEPRPIGTRYLTRNL",
    "AAV9":"MAADGYLPDWLEDNLSEGIREWWALKPGAPQPKANQQHQDNARGLVLPGYKYLGPGNGLDKGEPVNAADAAALEHDKAYDQQLKAGDNPYLKYNHADAEFQERLKEDTSFGGNLGRAVFQAKKRLLEPLGLVEEAAKTAPGKKRPVEQSPQEPDSSAGIGKSGAQPAKKRLNFGQTGDTESVPDPQPIGEPPAAPSGVGSLTMASGGGAPVADNNEGADGVGSSSGNWHCDSQWLGDRVITTSTRTWALPTYNNHLYKQISNSTSGGSSNDNAYFGYSTPWGYFDFNRFHCHFSPRDWQRLINNNWGFRPKRLNFKLFNIQVKEVTDNNGVKTIANNLTSTVQVFTDSDYQLPYVLGSAHEGCLPPFPADVFMIPQYGYLTLNDGSQAVGRSSFYCLEYFPSQMLRTGNNFQFSYEFENVPFHSSYAHSQSLDRLMNPLIDQYLYYLSKTINGSGQNQQTLKFSVAGPSNMAVQGRNYIPGPSYRQQRVSTTVTQNNNSEFAWPGASSWALNGRNSLMNPGPAMASHKEGEDRFFPLSGSLIFGKQGTGRDNVDADKVMITNEEEIKTTNPVATESYGQVATNHQSAQAQAQTGWVQNQGILPGMVWQDRDVYLQGPIWAKIPHTDGNFHPSPLMGGFGMKHPPPQILIKNTPVPADPPTAFNKDKLNSFITQYSTGQVSVEIEWELQKENSKRWNPEIQYTSNYYKSNNVEFAVNTEGVYSEPRPIGTRYLTRNL",
}

re_enzymes = { # K : V is Enzyme_Name : Recognition_Sequence
    # Type IIS Enzymes
    "BsaI": "GGTCTC",
    "Esp3I": "CGTCTC",
    "BsmBI": "CGTCTC",
    "PaqCI": "CACCTGC",

    # Type II Enzymes
    "SpeI": "ACTAGT",
    "HindIII": "AAGCTT",
    "SacI": "GAGCTC",
    "NotI": "GCGGCCGC",

    # Blunt Cutters
    "SwaI": "ATTTAAAT",
    "EcoRV": "GATATC",
    "ScaI": "AGTACT",

    # Double Cutters
    "BsaXI": "ACNNNNNCTCC",
    "AjuI": "GAANNNNNNNTTGG"
}

re_enzymes_regex = { # K : V is Enzyme_Name : Regex Pattern
    # Type IIS Enzymes
    "BsaI": "GGTCTC",
    "Esp3I": "CGTCTC",
    "BsmBI": "CGTCTC",
    "PaqCI": "CACCTGC",

    # Type II Enzymes
    "SpeI": "ACTAGT",
    "HindIII": "AAGCTT",
    "SacI": "GAGCTC",
    "NotI": "GCGGCCGC",

    # Blunt Cutters
    "SwaI": "ATTTAAAT",
    "EcoRV": "GATATC",
    "ScaI": "AGTACT",

    # Double Cutters
    "BsaXI": "AC[AGCTWSMKRYBDHVNX]{5}CTCC", # AC(N_5)CTCC
    "AjuI": "GAA[AGCTWSMKRYBDHVNX]{7}TTGG"  # GAA(N_7)TTGG
}

re_enzymes_inverted = {
    v : k for k, v in re_enzymes.items()
}

# These are of the form (A, B, C, D)
# A is the offset to reindex from the beginning of the enzyme recognition site
# B is the offset for both the end of the top strand and beginning of the bottom strand
# C is the cutter orientation, where BioOrientation.BOTTOM means the bottom overhangs the top, and BioOrientation.TOP means the opposite
re_enzymes_offsets = {
    # Type IIS Enzymes
    "BsaI": (7, 4, BioOrientation.BOTTOM),
    "Esp3I": (7, 4, BioOrientation.BOTTOM),
    "BsmBI": (7, 4, BioOrientation.BOTTOM),
    "PaqCI": (11, 4, BioOrientation.BOTTOM),

    # Type II Enzymes - Bottom Cutters
    "SpeI": (1, 4, BioOrientation.BOTTOM),
    "HindIII": (1, 4, BioOrientation.BOTTOM),
    "NotI": (2, 4, BioOrientation.BOTTOM),

    # Type II Enzymes - Top Cutters
    "SacI": (1, 4, BioOrientation.TOP),

    # Blunt Cutters
    "SwaI": (4, 0, BioOrientation.BOTTOM),
    "EcoRV": (3, 0, BioOrientation.BOTTOM),
    "ScaI": (3, 0, BioOrientation.BOTTOM),

    # Double Cutters
    "BsaXI": [(-12, 3, BioOrientation.TOP), (18, 3, BioOrientation.TOP)], # (9/12)ACNNNNNCTCC(10/7)
    "AjuI": [(-12, 5, BioOrientation.TOP), (20, 5, BioOrientation.TOP)] # (7/12)GAANNNNNNNTTGG(11/6)
}
